# Generated by Django 3.1.7 on 2025-02-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reg_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
