# Generated by Django 3.1.7 on 2025-02-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='uploaded_by',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
