# Generated by Django 3.1.7 on 2025-02-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20250204_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
